# General config options
[config]
tsHeaders = "no"                # synch ts headers
tsPoints = "yes"                # synch ts points
tsPointsWindowDays = "1"        # the time window (in days) for ts points synch
enableContextualization = "yes" # yes/no, try linking the TS headers to assets

# Filters specifying which time series to include in the replication
[blacklist]
tsExternalId = []
[whitelist]
tsExternalId = ["*"]