# General config options
[config]
sequenceHeaders = "yes"         # synch ts headers
sequenceRows = "yes"            # synch ts points
sequencePointsWindowDays = "1"  # the time window (in days) for ts points synch, use "-1" for full history
enableContextualization = "yes" # yes/no, try linking the Sequence headers to assets
enableDataSetMapping = "yes"    # yes/no, try mapping the source data set to target data set

# Filters specifying which time series to include in the replication
# The exact match on externalId is unioned with the regex expression.
# Example: "\\d" for digit, "\\\\" for backslash.
[denyList]
sequenceExternalId = []           # leave empty for no deny list
[allowList]
dataSetExternalId = ["*"]   # "*" includes all data sets
sequenceExternalId = ["*"]                       # include all TS